[build]
  command = "npm run build:static"
  publish = "dist/angular/browser"

# Skip the Angular SSR runtime plugin
[build.environment]
  NETLIFY_ANGULAR_SSR = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
