[build]
  command = "npm run build:static"
  publish = "dist/angular/browser"

# Disable the Angular runtime plugin entirely
[[plugins]]
  package = "@netlify/angular-runtime"
  
  [plugins.inputs]
    skip = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
